# Generated by Django 5.2.8 on 2025-11-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('colour', models.CharField()),
                ('price_range', models.IntegerField()),
            ],
        ),
    ]
